import type {
  Account,
  AccountingRule,
  DatevExportJob,
  DuplicateItem,
  ImportBatch,
  PatternGroup,
  ReconciliationSummary,
  Transaction,
  CompanySettings,
  DatevSettings,
} from "@/types/accounting";

export const mockAccounts: Account[] = [
  {
    id: "acc-4400",
    number: "4400",
    name: "Wareneingang",
    type: "expense",
    description: "Einkauf Waren / Inventory",
    status: "active",
  },
  {
    id: "acc-4910",
    number: "4910",
    name: "Porto / Versand",
    type: "expense",
    description: "Shipping & postage",
    status: "active",
  },
  {
    id: "acc-4970",
    number: "4970",
    name: "Nebenkosten des Geldverkehrs",
    type: "expense",
    description: "Bank / PayPal fees",
    status: "active",
  },
  {
    id: "acc-1200",
    number: "1200",
    name: "Bank",
    type: "offset",
    description: "Bankkonto",
    status: "active",
  },
  {
    id: "acc-1360",
    number: "1360",
    name: "PayPal",
    type: "offset",
    description: "PayPal-Konto",
    status: "active",
  },
  {
    id: "acc-8400",
    number: "8400",
    name: "Erlöse 19% USt",
    type: "revenue",
    description: "Umsatzerlöse",
    status: "active",
  },
];

export const mockRules: AccountingRule[] = [
  {
    id: "rule-1",
    name: "DHL Versand",
    keywords: ["DHL", "DEUTSCHE POST"],
    matchMode: "contains",
    caseSensitive: false,
    expenseAccountId: "acc-4910",
    offsetAccountId: "acc-1200",
    priority: 10,
    enabled: true,
    version: 3,
    matchCount: 42,
    createdAt: "2026-01-12T10:00:00.000Z",
    updatedAt: "2026-07-01T09:00:00.000Z",
    history: [
      {
        id: "rh-1",
        version: 3,
        changedAt: "2026-07-01T09:00:00.000Z",
        changedBy: "Admin",
        summary: "Keyword DEUTSCHE POST hinzugefügt",
      },
    ],
  },
  {
    id: "rule-2",
    name: "Amazon Einkauf",
    keywords: ["AMAZON", "AMZN"],
    matchMode: "contains",
    caseSensitive: false,
    expenseAccountId: "acc-4400",
    offsetAccountId: "acc-1200",
    priority: 20,
    enabled: true,
    version: 2,
    matchCount: 88,
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-06-15T11:00:00.000Z",
    history: [],
  },
  {
    id: "rule-3",
    name: "PayPal Gebühren",
    keywords: ["PAYPAL", "FEE"],
    matchMode: "contains",
    caseSensitive: false,
    expenseAccountId: "acc-4970",
    offsetAccountId: "acc-1360",
    priority: 5,
    enabled: true,
    version: 1,
    matchCount: 31,
    createdAt: "2026-03-10T10:00:00.000Z",
    updatedAt: "2026-03-10T10:00:00.000Z",
    history: [],
  },
];

function tx(
  partial: Omit<Transaction, "history" | "currency" | "exportStatus"> &
    Partial<Pick<Transaction, "history" | "currency" | "exportStatus">>
): Transaction {
  return {
    currency: "EUR",
    exportStatus: "not_exported",
    history: [
      {
        id: `${partial.id}-h1`,
        at: partial.date,
        action: "imported",
        actor: "System",
        detail: "CSV-Import",
      },
    ],
    ...partial,
  };
}

export const mockTransactions: Transaction[] = [
  tx({
    id: "tx-1",
    date: "2026-07-28",
    transactionId: "BANK-1001",
    source: "bank",
    counterparty: "DHL Paket GmbH",
    description: "DHL Versand Juli",
    reference: "INV-DHL-7781",
    amount: -48.9,
    status: "matched",
    matchedRuleId: "rule-1",
    confidence: 96,
    expenseAccountId: "acc-4910",
    offsetAccountId: "acc-1200",
    suggestedKeywords: ["DHL"],
    hash: "h1",
    importBatchId: "batch-bank-1",
  }),
  tx({
    id: "tx-2",
    date: "2026-07-27",
    transactionId: "BANK-1002",
    source: "bank",
    counterparty: "Amazon EU S.a.r.l.",
    description: "AMAZON MARKETPLACE Einkauf",
    reference: "303-889911",
    amount: -129.99,
    status: "matched",
    matchedRuleId: "rule-2",
    confidence: 94,
    expenseAccountId: "acc-4400",
    offsetAccountId: "acc-1200",
    suggestedKeywords: ["AMAZON"],
    hash: "h2",
    importBatchId: "batch-bank-1",
  }),
  tx({
    id: "tx-3",
    date: "2026-07-26",
    transactionId: "PP-9001",
    source: "paypal",
    counterparty: "PayPal Europe",
    description: "PayPal Gebühr Transaktion",
    reference: "FEE-9001",
    amount: -1.79,
    status: "suggested",
    suggestedRuleId: "rule-3",
    confidence: 88,
    suggestedKeywords: ["PAYPAL", "FEE"],
    expenseAccountId: "acc-4970",
    offsetAccountId: "acc-1360",
    hash: "h3",
    importBatchId: "batch-pp-1",
  }),
  tx({
    id: "tx-4",
    date: "2026-07-25",
    transactionId: "BANK-1003",
    source: "bank",
    counterparty: "UPS Deutschland",
    description: "UPS Express Versand",
    reference: "1Z999",
    amount: -62.4,
    status: "suggested",
    confidence: 72,
    suggestedKeywords: ["UPS", "VERSAND"],
    hash: "h4",
    importBatchId: "batch-bank-1",
  }),
  tx({
    id: "tx-5",
    date: "2026-07-24",
    transactionId: "BANK-1004",
    source: "bank",
    counterparty: "Kunde Müller GmbH",
    description: "Zahlung Rechnung 4521",
    reference: "RE-4521",
    amount: 890.0,
    status: "new",
    hash: "h5",
    importBatchId: "batch-bank-1",
  }),
  tx({
    id: "tx-6",
    date: "2026-07-23",
    transactionId: "PP-9002",
    source: "paypal",
    counterparty: "Supplier Parts Ltd",
    description: "Inventory purchase batch",
    reference: "PO-221",
    amount: -340.5,
    status: "approved",
    expenseAccountId: "acc-4400",
    offsetAccountId: "acc-1360",
    confidence: 90,
    exportStatus: "exported",
    hash: "h6",
    importBatchId: "batch-pp-1",
  }),
  tx({
    id: "tx-7",
    date: "2026-07-22",
    transactionId: "BANK-1005",
    source: "bank",
    counterparty: "DHL Paket GmbH",
    description: "DHL Express Nachnahme",
    reference: "INV-DHL-7800",
    amount: -55.2,
    status: "exported",
    matchedRuleId: "rule-1",
    expenseAccountId: "acc-4910",
    offsetAccountId: "acc-1200",
    exportStatus: "exported",
    confidence: 97,
    hash: "h7",
    importBatchId: "batch-bank-1",
  }),
  tx({
    id: "tx-8",
    date: "2026-07-21",
    transactionId: "BANK-1002-DUP",
    source: "bank",
    counterparty: "Amazon EU S.a.r.l.",
    description: "AMAZON MARKETPLACE Einkauf",
    reference: "303-889911",
    amount: -129.99,
    status: "duplicate",
    hash: "h2",
    importBatchId: "batch-bank-2",
  }),
];

export const mockImportBatches: ImportBatch[] = [
  {
    id: "batch-bank-1",
    source: "bank",
    fileName: "bank_2026-07.csv",
    fileHash: "sha-bank-1",
    importedAt: "2026-07-28T08:00:00.000Z",
    rowCount: 6,
    successCount: 6,
    errorCount: 0,
    duplicateCount: 0,
    status: "completed",
    errors: [],
  },
  {
    id: "batch-pp-1",
    source: "paypal",
    fileName: "paypal_2026-07.csv",
    fileHash: "sha-pp-1",
    importedAt: "2026-07-27T09:30:00.000Z",
    rowCount: 2,
    successCount: 2,
    errorCount: 0,
    duplicateCount: 0,
    status: "completed",
    errors: [],
  },
];

export const mockPatterns: PatternGroup[] = [
  {
    id: "pat-1",
    keyword: "DHL",
    confidence: 96,
    transactionIds: ["tx-1", "tx-7"],
    suggestedRuleName: "DHL Versand",
    expenseAccountId: "acc-4910",
    offsetAccountId: "acc-1200",
    status: "pending",
  },
  {
    id: "pat-2",
    keyword: "UPS",
    confidence: 72,
    transactionIds: ["tx-4"],
    suggestedRuleName: "UPS Versand",
    expenseAccountId: "acc-4910",
    offsetAccountId: "acc-1200",
    status: "pending",
  },
  {
    id: "pat-3",
    keyword: "AMAZON",
    confidence: 94,
    transactionIds: ["tx-2"],
    suggestedRuleName: "Amazon Einkauf",
    expenseAccountId: "acc-4400",
    offsetAccountId: "acc-1200",
    status: "rule_created",
  },
];

export const mockExports: DatevExportJob[] = [
  {
    id: "exp-1",
    period: "monthly",
    from: "2026-07-01",
    to: "2026-07-31",
    transactionCount: 2,
    createdAt: "2026-08-01T10:00:00.000Z",
    createdBy: "Admin",
    status: "completed",
    warnings: ["2 Transaktionen ohne Gegenkonto übersprungen"],
    errors: [],
    fileName: "EXTF_Buchungsstapel_2026-07.csv",
  },
];

export const mockDuplicates: DuplicateItem[] = [
  {
    id: "dup-1",
    kind: "possible_duplicate",
    transactionIds: ["tx-2", "tx-8"],
    reason: "Gleicher Hash / Betrag / Referenz",
  },
  {
    id: "dup-2",
    kind: "already_exported",
    transactionIds: ["tx-6", "tx-7"],
    reason: "Bereits in DATEV-Export enthalten",
  },
];

export const mockReconciliation: ReconciliationSummary = {
  importedAmount: -778.77,
  exportedAmount: -395.7,
  difference: -383.07,
  missingCount: 3,
  duplicateCount: 1,
  validationStatus: "unbalanced",
};

export const mockCompanySettings: CompanySettings = {
  companyName: "BuyBack GmbH",
  taxId: "DE123456789",
  street: "Musterstraße 12",
  city: "Berlin",
  postalCode: "10115",
  country: "DE",
};

export const mockDatevSettings: DatevSettings = {
  consultantNumber: "12345",
  clientNumber: "67890",
  chartOfAccounts: "SKR03",
  fiscalYearStart: "2026-01-01",
  defaultExpenseAccount: "4400",
  defaultOffsetAccount: "1200",
};
